services:
  solace-db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      - psql:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d/ # For initialization script
    ports:
      - 5432:5432
volumes:
  psql:
